Update MakeFile

diff --git a/root/etc/uci-defaults/99_rakitiw b/root/etc/uci-defaults/99_rakitiw
--- a/root/etc/uci-defaults/99_rakitiw
+++ b/root/etc/uci-defaults/99_rakitiw
@@ -1,6 +1,27 @@
-#!/bin/sh
+#!/bin/bash
+# Copyright 2024 RTA SERVER
 
-echo "Setup Rakitiw"
+log_file="/var/log/rakitanmanager.log"
+exec 1>>"$log_file" 2>&1
+log() {
+    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
+}
+
+log "Setup Modem Rakitiw"
+rpid=$(pgrep "rakitanmanager")
+if [[ -n $rpid ]]; then
+    kill $rpid
+fi
+
+log "Setup php uhttpd"
+uci set uhttpd.main.index_page='index.php'
+uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
+uci commit uhttpd
+
+/etc/init.d/uhttpd restart
+log "Setup php uhttpd Done"
+
+log "Setup ModemManager"
 mm1="/usr/lib/ModemManager/connection.d/10-report-down"
 mm2="/usr/lib/ModemManager/connection.d/10-report-down-and-reconnect"
 
@@ -13,25 +34,31 @@ fi
 
 mv "/usr/lib/ModemManager/connection.d/rakitiw" "/usr/lib/ModemManager/connection.d/10-report-down-and-reconnect"
 chmod +x /usr/lib/ModemManager/connection.d/10-report-down-and-reconnect
+log "Setup ModemManager Done"
 
+log "Setup Package For Python3"
 if which pip3 >/dev/null; then
     # Instal paket 'requests' jika belum terinstal
     if ! pip3 show requests >/dev/null; then
-        echo "Installing package 'requests'"
-        pip3 install requests
+        log "Installing package 'requests'"
+        if ! pip3 install requests >>"$log_file" 2>&1; then
+            log "Error installing package 'requests'"
+        fi
     else
-        echo "Package 'requests' already installed"
+        log "Package 'requests' already installed"
     fi
 
     # Instal paket 'huawei-lte-api' jika belum terinstal
     if ! pip3 show huawei-lte-api >/dev/null; then
-        echo "Installing package 'huawei-lte-api'"
-        pip3 install huawei-lte-api
+        log "Installing package 'huawei-lte-api'"
+        if ! pip3 install huawei-lte-api >>"$log_file" 2>&1; then
+            log "Error installing package 'huawei-lte-api'"
+        fi
     else
-        echo "Package 'huawei-lte-api' already installed"
+        log "Package 'huawei-lte-api' already installed"
     fi
 else
-    echo "Error: 'pip3' command not found"
+    log "Error: 'pip3' command not found"
 fi
 
-echo "Setup Done"
+log "Setup Done | Modem Rakitiw Berhasil Di Install"
